// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class Categories
    {
        public Categories()
        {
            Products = new HashSet<Products>();
        }

        [Key]
        public long CatId { get; set; }
        [Required]
        [StringLength(60)]
        public string CatName { get; set; }
        public int CatActive { get; set; }

        [InverseProperty("Cat")]
        public virtual ICollection<Products> Products { get; set; }
    }
}