// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class Products
    {
        public Products()
        {
            ProductPrices = new HashSet<ProductPrices>();
        }

        [Key]
        public long ProdId { get; set; }
        [Required]
        [StringLength(60)]
        public string ProdName { get; set; }
        [Required]
        [StringLength(60)]
        public string ProdBarcode { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ProdExpiry { get; set; }
        public long CatId { get; set; }

        [ForeignKey("CatId")]
        [InverseProperty("Products")]
        public virtual Categories Cat { get; set; }
        [InverseProperty("ProdPriceProduct")]
        public virtual ICollection<ProductPrices> ProductPrices { get; set; }
    }
}