// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class ProductPrices
    {
        [Key]
        public long ProdPriceId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProdPriceBuyingPrice { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ProdPriceSellingPrice { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ProdPriceBuyingDate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ProdPriceProfit { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ProdPriceDiscount { get; set; }
        public string ProdPriceBarcode { get; set; }
        public long ProdPriceProductId { get; set; }

        [ForeignKey("ProdPriceProductId")]
        [InverseProperty("ProductPrices")]
        public virtual Products ProdPriceProduct { get; set; }
    }
}