// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class PurchaseInvoices
    {
        public PurchaseInvoices()
        {
            PurchaseInvoiceDetails = new HashSet<PurchaseInvoiceDetails>();
        }

        [Key]
        [Column("PIid")]
        public long Piid { get; set; }
        [Column("PIDate")]
        public DateTime Pidate { get; set; }
        public long SuppId { get; set; }

        [InverseProperty("PidpurchaseInvoice")]
        public virtual ICollection<PurchaseInvoiceDetails> PurchaseInvoiceDetails { get; set; }
    }
}