// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class PurchaseInvoiceDetails
    {
        [Key]
        [Column("PIDId")]
        public long Pidid { get; set; }
        [Column("PIDProductId")]
        public long PidproductId { get; set; }
        [Column("PIDProductQuantity")]
        public long PidproductQuantity { get; set; }
        [Column("PIDProductTotalPrice", TypeName = "decimal(18, 2)")]
        public decimal PidproductTotalPrice { get; set; }
        [Column("PIDPerUnitPrice", TypeName = "decimal(18, 2)")]
        public decimal? PidperUnitPrice { get; set; }
        [Column("PIDPurchaseInvoiceId")]
        public long PidpurchaseInvoiceId { get; set; }

        [ForeignKey("PidpurchaseInvoiceId")]
        [InverseProperty("PurchaseInvoiceDetails")]
        public virtual PurchaseInvoices PidpurchaseInvoice { get; set; }
    }
}