// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class Sales
    {
        [Key]
        public long SalId { get; set; }
        public DateTime SalDate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SalTotalAmount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? SalTotalDiscount { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SalAmountGiven { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SalAmountReturn { get; set; }
        public int SalPayType { get; set; }

        [InverseProperty("SalDet")]
        public virtual SaleDetails SaleDetails { get; set; }
    }
}