// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class SaleDetails
    {
        [Key]
        public long SalDetId { get; set; }
        public long SalDetProductId { get; set; }
        public int SalDetQuanity { get; set; }
        public long SalDetSaleId { get; set; }

        [ForeignKey("SalDetId")]
        [InverseProperty("SaleDetails")]
        public virtual Sales SalDet { get; set; }
    }
}