// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagementSystem.Models
{
    public partial class st_getPurchaseInvoiceListResult
    {
        public long ID { get; set; }
        [Column("Company Name")]
        public string CompanyName { get; set; }
    }
}
