// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagementSystem.Models
{
    public partial class st_getCategoriesResult
    {
        public long ID { get; set; }
        public string Category { get; set; }
        public string Status { get; set; }
    }
}
