// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagementSystem.Models
{
    public partial class st_getPurchaseInvoiceDetailsResult
    {
        [Column("Purchase Invoice Details ID")]
        public long PurchaseInvoiceDetailsID { get; set; }
        [Column("Product ID")]
        public long ProductID { get; set; }
        [Column("Product Name")]
        public string ProductName { get; set; }
        public long Quantity { get; set; }
        [Column("Total Price")]
        public decimal TotalPrice { get; set; }
        [Column("Per unit Price")]
        public decimal PerunitPrice { get; set; }
    }
}
