// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagementSystem.Models
{
    public partial class st_getProductswrtCategoriesResult
    {
        [Column("Product ID")]
        public long ProductID { get; set; }
        public string Product { get; set; }
        [Column("Buying Price")]
        public decimal BuyingPrice { get; set; }
    }
}
