// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagementSystem.Models
{
    public partial class st_searchProductsResult
    {
        public long ID { get; set; }
        public string Product { get; set; }
        public string Barcode { get; set; }
        public DateTime? Expiry { get; set; }
        [Column("Category ID")]
        public long CategoryID { get; set; }
        public string Category { get; set; }
    }
}
