// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class Stocks
    {
        [Key]
        public long StockId { get; set; }
        public long StockProductId { get; set; }
        public int StockQuantity { get; set; }
    }
}