// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagementSystem.Models
{
    public partial class Suppliers
    {
        [Key]
        public long SuppId { get; set; }
        [Required]
        [StringLength(60)]
        public string SuppName { get; set; }
        [Required]
        [StringLength(60)]
        public string SuppPersonName { get; set; }
        [Required]
        [StringLength(11)]
        public string SuppPhone1 { get; set; }
        [StringLength(11)]
        public string SuppPhone2 { get; set; }
        [Required]
        [StringLength(60)]
        public string SuppAddress { get; set; }
        [Required]
        [Column("SuppNTN")]
        [StringLength(60)]
        public string SuppNtn { get; set; }
        public bool SuppActive { get; set; }
    }
}